### ISSUE TITLE
grom AutoMigrate无法使用， 更新字段或者索引失败

### ISSUE THREAD

**Issue by shuaiganzi** [klen-ygs/gorm-zero#1]
基于template生成的模版会被 `` 包裹，导致AutoMigrate auto migrate 时判断表不存，一直进行表创建
![image](https://github.com/klen-ygs/gorm-zero/assets/42165666/ff108681-11db-4a78-8a2f-1696aa7a9725)

gorm.io/gorm@v1.25.7/migrator/migrator.go:322
![image](https://github.com/klen-ygs/gorm-zero/assets/42165666/226753cc-cfd9-4a9e-8dbb-ba7ae6373cbb)

如果修改去掉``包裹表名，则恢复正常使用

**Comment by klen-ygs** [comment]
感谢你的反馈,现在生成的代码如下图,测试没问题的话明天会发新版
![Screenshot_20240221_140902](https://github.com/klen-ygs/gorm-zero/assets/105289582/e275b11d-477b-4d4b-8f2f-04bb6246dff8)
