### ISSUE TITLE
trace 不一致，请问是什么情况呀

### ISSUE THREAD

**Issue by jaronnie** [klen-ygs/gorm-zero#4]
<img width="1397" alt="image" src="https://github.com/klen-ygs/gorm-zero/assets/77253497/ace321fb-1339-41e5-abdf-99ce2aa79633">

**Comment by klen-ygs** [comment]
使用db时是否携带了 ctx
```
err = c.conn.
		WithContext(ctx).
		Where(Between(&QStudent.Age, start, ent)).
		Find(&resp).
		Error
```
